/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--color-bg-dim)",
        surface: "var(--color-bg-surface)",
        "surface-container": "var(--color-bg-card)",
        "surface-container-lowest": "var(--color-surface-lowest)",
        "surface-container-highest": "var(--color-surface-highest)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-hover": "var(--color-surface-hover)",
        "text-primary": "var(--color-text-main)",
        "on-surface": "var(--color-text-main)",
        "on-background": "var(--color-text-main)",
        "text-muted": "var(--color-text-muted)",
        "text-dim": "var(--color-text-dim)",
        primary: "var(--color-primary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-container": "var(--color-on-primary-container)",
        secondary: "var(--color-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        tertiary: "var(--color-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "border-muted": "var(--color-border)",
        "border-glow": "var(--color-border-glow)",
        "severity-high": "var(--color-severity-high)",
        "severity-medium": "var(--color-severity-medium)",
        "severity-low": "var(--color-severity-low)",
        "severity-high-bg": "var(--color-severity-high-bg)",
        "severity-high-border": "var(--color-severity-high-border)",
        "severity-medium-bg": "var(--color-severity-medium-bg)",
        "severity-medium-border": "var(--color-severity-medium-border)",
        "severity-low-bg": "var(--color-severity-low-bg)",
        "severity-low-border": "var(--color-severity-low-border)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
